# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mycli < Formula
  desc "My CLI demo"
  homepage "https://github.com/cronchiq/mycli"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cronchiq/mycli/releases/download/v0.2.2/mycli_v0.2.2_darwin_arm64.tar.gz"
      sha256 "6977aec50ec50916d25823575f2757da68e41b8b673a8af3deb23f3a88bf870b"

      def install
        bin.install "mycli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cronchiq/mycli/releases/download/v0.2.2/mycli_v0.2.2_darwin_amd64.tar.gz"
      sha256 "c99b600b2994b9f6feac95fa69cec26a08105edf0fca83ec75296ebb63b14e0d"

      def install
        bin.install "mycli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cronchiq/mycli/releases/download/v0.2.2/mycli_v0.2.2_linux_amd64.tar.gz"
      sha256 "e404a42a8a7c4f35d2164c17c88dc3fc9cb64316302b696bcc08c867fad807ea"

      def install
        bin.install "mycli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cronchiq/mycli/releases/download/v0.2.2/mycli_v0.2.2_linux_arm64.tar.gz"
      sha256 "bfaf854ee8ce9d6a9c40612d1056c93bfed8b5c3d3ca6851c533015ba0814e1b"

      def install
        bin.install "mycli"
      end
    end
  end

  conflicts_with "slu-edge"

  def caveats; <<~EOS
    How to use this binary: https://github.com/cronchiq/mycli
  EOS
  end

  test do
    system "#{bin}/mycli"
  end
end
