# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mycli < Formula
  desc "My CLI demo"
  homepage "https://github.com/cronchiq/mycli"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cronchiq/mycli/releases/download/v0.1.5/mycli_v0.1.5_darwin_arm64.tar.gz"
      sha256 "dd0e5849aa0b1b80fed8e3018b6e6aaf91b873e2085f320482383622bb6b2bf5"

      def install
        bin.install "mycli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cronchiq/mycli/releases/download/v0.1.5/mycli_v0.1.5_darwin_amd64.tar.gz"
      sha256 "70853484e06c1c7a00a4ae617cda19352716362db6526c28e72af00351026598"

      def install
        bin.install "mycli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cronchiq/mycli/releases/download/v0.1.5/mycli_v0.1.5_linux_amd64.tar.gz"
      sha256 "a8d2ef372f40b55da16ef654f51a3978ac99e746884c837a678ba956a3b65f17"

      def install
        bin.install "mycli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cronchiq/mycli/releases/download/v0.1.5/mycli_v0.1.5_linux_arm64.tar.gz"
      sha256 "5ab34c27638b716195afd18dcd05a797fe1451c9cf0240d8f32d00d23e43a8d0"

      def install
        bin.install "mycli"
      end
    end
  end

  conflicts_with "slu-edge"

  def caveats; <<~EOS
    How to use this binary: https://github.com/cronchiq/mycli
  EOS
  end

  test do
    system "#{bin}/mycli"
  end
end
