# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mycli < Formula
  desc "My CLI demo"
  homepage "https://github.com/cronchiq/mycli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cronchiq/mycli/releases/download/v0.1.2/mycli_v0.1.2_darwin_arm64.tar.gz"
      sha256 "d3690966cc56f0da268f9180d0f93b16d0611acf38c2b79302f886a66c882943"

      def install
        bin.install "mycli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cronchiq/mycli/releases/download/v0.1.2/mycli_v0.1.2_darwin_amd64.tar.gz"
      sha256 "d7eb720836737d166286930338392fd9e5df0f7cf570906b71cbdb66a2de8673"

      def install
        bin.install "mycli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cronchiq/mycli/releases/download/v0.1.2/mycli_v0.1.2_linux_amd64.tar.gz"
      sha256 "a4e51af3f8246e36d8c6a932fa909ab80fe5285c46a71fc9f0499c141cfc3138"

      def install
        bin.install "mycli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cronchiq/mycli/releases/download/v0.1.2/mycli_v0.1.2_linux_arm64.tar.gz"
      sha256 "e46540ecfb4f73c23ff238e72d63235016f69932fa56d220008297fc608b81a6"

      def install
        bin.install "mycli"
      end
    end
  end

  conflicts_with "slu-edge"

  def caveats; <<~EOS
    How to use this binary: https://github.com/cronchiq/mycli
  EOS
  end

  test do
    system "#{bin}/mycli"
  end
end
